kind: pipeline
type: ssh
name: deploy_prod_frontend

server:
  host:
    from_secret: ssh_host_prod
  user: root
  password:
    from_secret: ssh_password_prod

steps:
  - name: deploy
    environment:
      COMPOSE_PROJECT_NAME: webservicesjitcom
    commands:
      - docker compose -f docker-compose_prod.yaml build
      - docker compose -f docker-compose_prod.yaml up -d

trigger:
  branch:
    - prod
  event:
    - push

---

kind: pipeline
type: ssh
name: deploy_prod

server:
  host:
    from_secret: ssh_host_prod
  user: root
  password:
    from_secret: ssh_password_prod

steps:
  - name: deploy
    environment:
      COMPOSE_PROJECT_NAME: webservicesjitcom
    commands:
      - docker compose -f docker-compose_dev.yaml build
      - docker compose -f docker-compose_dev.yaml up -d

trigger:
  branch:
    - dev
  event:
    - push
