version: "3"

services:
  dev-sg-frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        STAGE: dev
    networks:
      - jitcom_net

networks:
  jitcom_net:
    external: true